---
    kind: pipeline
    name: mon-super-pipeline-ci
    
    steps:
    - name: hello-world
      image: lowess/preact-cli:latest
      commands:
      - npx preact-cli create Jojol8/preact-hugo test