---
    kind: pipeline
    name: mon-super-pipeline-ci
    
    steps:
    - name: hello-world
      image: lowess/preact-cli:latest
      commands:
      - npx preact-cli create Jojol8/preact-hugo test
      - npm install
      - npm build
    - name: slack-notif
      image: plugins/slack:latest
      settings:
        webhook:
          from_secret: slack
        channel: drone-ci
        username: JojoTheBest
        icon_url: https://static.lexpress.fr/medias_4728/w_930%2Ch_404%2Cc_crop%2Cx_0%2Cy_107/w_640%2Ch_360%2Cc_fill%2Cg_north/v1404791598/jean-marie-le-pen-au-rassemblement-du-fn-le-1er-mai-2013_2421072.jpg
        template: >
          {{#succes build.status}}
            {{build.number}} ok
          {{else}}
            {{build.number}} ko
          {{/success}}